# Generated by Django 5.1.5 on 2026-04-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_corevalue_ourstory_program_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'our_impact',
            },
        ),
    ]
